#!/usr/bin/env node
/**
 * scripts/dump-sql.ts
 *
 * Generates a complete bootstrap SQL file (schema + seed) that can be
 * pasted into hPanel's phpMyAdmin or run via mysql CLI to populate a
 * fresh database from scratch.
 *
 *   npx tsx scripts/dump-sql.ts > docs/db-bootstrap.sql
 */
import { readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

interface Spec {
  label: string
  value: string
}
interface Product {
  id: string
  slug: string
  name: string
  category: string
  price: number
  tagline: string
  description: string
  specs: Spec[]
  swatch: string
  inStock: boolean
  hasPhotos: boolean
  featured?: boolean
  stockQty?: number
  lowStockThreshold?: number
}
interface Category {
  id: string
  name: string
  description: string
  order: number
}

function esc(s: string): string {
  return s.replace(/'/g, "''").replace(/\\/g, '\\\\')
}

function bool(b: boolean): string {
  return b ? '1' : '0'
}

function main(): void {
  const root = resolve(__dirname, '..')
  const schema = readFileSync(
    join(root, 'src/db/migrations/0000_short_junta.sql'),
    'utf8',
  )
    .replace(/--> statement-breakpoint/g, '')
    .replace(/\n{3,}/g, '\n\n')

  const cats = JSON.parse(
    readFileSync(join(root, 'src/data/categories.json'), 'utf8'),
  ) as Category[]
  const prods = JSON.parse(
    readFileSync(join(root, 'src/data/products.json'), 'utf8'),
  ) as Product[]

  let out = ''
  out += '-- merxylab-store bootstrap SQL\n'
  out += '-- Generated by scripts/dump-sql.ts\n'
  out += '-- Run order: schema -> reference data (divisions, payment_methods, categories) -> products + specs\n\n'

  out += '-- =================================================================\n'
  out += '-- 1. Schema\n'
  out += '-- =================================================================\n'
  out += schema.trim() + '\n\n'

  out += '-- =================================================================\n'
  out += '-- 2. Divisions (BeeExpress shipping rates)\n'
  out += '-- =================================================================\n'
  const DIVISIONS = [
    ['mandalay', 'Mandalay Region', 3000, 1, 0, 1],
    ['yangon', 'Yangon Region', 5000, 1, 0, 2],
    ['naypyidaw', 'Naypyidaw Union Territory', 5000, 0, 0, 3],
    ['bago', 'Bago Region', 5750, 0, 0, 4],
    ['magway', 'Magway Region', 5750, 0, 0, 5],
    ['ayeyarwady', 'Ayeyarwady Region', 6250, 0, 0, 6],
    ['chin', 'Chin State', 6250, 0, 0, 7],
    ['mon', 'Mon State', 6250, 0, 0, 8],
    ['shan', 'Shan State', 6500, 0, 0, 9],
    ['rakhine', 'Rakhine State', 7000, 0, 0, 10],
    ['kachin', 'Kachin State', 8500, 0, 0, 11],
    ['tanintharyi', 'Tanintharyi Region', 8500, 0, 0, 12],
    ['kayah', 'Kayah State', 0, 0, 1, 13],
    ['kayin', 'Kayin State', 0, 0, 1, 14],
    ['sagaing', 'Sagaing Region', 0, 0, 1, 15],
  ] as const
  out += 'INSERT INTO `divisions` (`id`, `name`, `delivery_fee_mmk`, `cod_allowed`, `is_blocked`, `sort_order`) VALUES\n'
  out += DIVISIONS.map(
    ([id, name, fee, cod, blk, sort]) =>
      `('${id}', '${esc(name)}', ${fee}, ${cod}, ${blk}, ${sort})`,
  ).join(',\n')
  out += ';\n\n'

  out += '-- =================================================================\n'
  out += '-- 3. Payment methods (all inactive — owner activates via /admin)\n'
  out += '-- =================================================================\n'
  out += 'INSERT INTO `payment_methods` (`id`, `name`, `kind`, `sort_order`, `is_active`) VALUES\n'
  out += [
    `('kbz_pay', 'KBZ Pay', 'wallet', 1, 0)`,
    `('aya_pay', 'Aya Pay', 'wallet', 2, 0)`,
    `('uab_pay', 'UAB Pay', 'wallet', 3, 0)`,
    `('cod', 'Cash on Delivery', 'cod', 4, 0)`,
  ].join(',\n')
  out += ';\n\n'

  out += '-- =================================================================\n'
  out += '-- 4. Categories\n'
  out += '-- =================================================================\n'
  out += 'INSERT INTO `categories` (`id`, `name`, `description`, `sort_order`) VALUES\n'
  out += cats
    .map(
      (c) =>
        `('${c.id}', '${esc(c.name)}', '${esc(c.description)}', ${c.order})`,
    )
    .join(',\n')
  out += ';\n\n'

  out += '-- =================================================================\n'
  out += '-- 5. Products\n'
  out += '-- =================================================================\n'
  out += 'INSERT INTO `products` (`id`, `slug`, `name`, `category_id`, `price_mmk`, `tagline`, `description`, `swatch`, `stock_qty`, `low_stock_threshold`, `has_photos`, `is_active`, `featured`) VALUES\n'
  out += prods
    .map((p) => {
      const stockQty = p.stockQty ?? (p.inStock ? 10 : 0)
      const lowThresh = p.lowStockThreshold ?? 3
      return `('${p.id}', '${p.slug}', '${esc(p.name)}', '${p.category}', ${p.price}, '${esc(p.tagline)}', '${esc(p.description)}', '${p.swatch}', ${stockQty}, ${lowThresh}, ${bool(p.hasPhotos)}, 1, ${bool(p.featured ?? false)})`
    })
    .join(',\n')
  out += ';\n\n'

  out += '-- =================================================================\n'
  out += '-- 6. Product specs\n'
  out += '-- =================================================================\n'
  out += 'INSERT INTO `product_specs` (`product_id`, `label`, `value`, `sort_order`) VALUES\n'
  const specRows: string[] = []
  for (const p of prods) {
    p.specs.forEach((s, i) => {
      specRows.push(`('${p.id}', '${esc(s.label)}', '${esc(s.value)}', ${i})`)
    })
  }
  out += specRows.join(',\n')
  out += ';\n\n'

  out += '-- =================================================================\n'
  out += '-- Bootstrap complete.\n'
  out += '-- Next steps (manual, via SSH or phpMyAdmin):\n'
  out += "--   UPDATE users SET role='admin' WHERE email='you@example.com';\n"
  out += '-- =================================================================\n'

  process.stdout.write(out)
}

main()
