-- merxylab-store bootstrap SQL
-- Generated by scripts/dump-sql.ts
-- Run order: schema -> reference data (divisions, payment_methods, categories) -> products + specs

-- =================================================================
-- 1. Schema
-- =================================================================
CREATE TABLE `addresses` (
	`id` varchar(36) NOT NULL,
	`user_id` varchar(36) NOT NULL,
	`label` varchar(40) NOT NULL,
	`recipient` varchar(120) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`division_id` varchar(40) NOT NULL,
	`city` varchar(120) NOT NULL,
	`township` varchar(120) NOT NULL,
	`street` varchar(200) NOT NULL,
	`landmark` varchar(200),
	`is_default` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `addresses_id` PRIMARY KEY(`id`)
);

CREATE TABLE `accounts` (
	`userId` varchar(36) NOT NULL,
	`type` varchar(40) NOT NULL,
	`provider` varchar(80) NOT NULL,
	`providerAccountId` varchar(200) NOT NULL,
	`refresh_token` text,
	`access_token` text,
	`expires_at` int,
	`token_type` varchar(40),
	`scope` varchar(500),
	`id_token` text,
	`session_state` varchar(500),
	CONSTRAINT `accounts_provider_providerAccountId_pk` PRIMARY KEY(`provider`,`providerAccountId`)
);

CREATE TABLE `sessions` (
	`session_token` varchar(255) NOT NULL,
	`user_id` varchar(36) NOT NULL,
	`expires` timestamp NOT NULL,
	CONSTRAINT `sessions_session_token` PRIMARY KEY(`session_token`)
);

CREATE TABLE `users` (
	`id` varchar(36) NOT NULL,
	`name` varchar(120),
	`email` varchar(254) NOT NULL,
	`email_verified` timestamp(3),
	`password_hash` varchar(60),
	`image` varchar(500),
	`role` enum('customer','admin') NOT NULL DEFAULT 'customer',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`)
);

CREATE TABLE `verification_tokens` (
	`identifier` varchar(254) NOT NULL,
	`token` varchar(255) NOT NULL,
	`expires` timestamp NOT NULL,
	CONSTRAINT `verification_tokens_identifier_token_pk` PRIMARY KEY(`identifier`,`token`)
);

CREATE TABLE `cart_items` (
	`cart_id` varchar(36) NOT NULL,
	`product_id` varchar(64) NOT NULL,
	`qty` int NOT NULL,
	`added_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cart_items_cart_id_product_id_pk` PRIMARY KEY(`cart_id`,`product_id`)
);

CREATE TABLE `carts` (
	`id` varchar(36) NOT NULL,
	`user_id` varchar(36),
	`session_id` varchar(36),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `carts_id` PRIMARY KEY(`id`)
);

CREATE TABLE `divisions` (
	`id` varchar(40) NOT NULL,
	`name` varchar(60) NOT NULL,
	`delivery_fee_mmk` bigint NOT NULL,
	`cod_allowed` boolean NOT NULL DEFAULT false,
	`is_blocked` boolean NOT NULL DEFAULT false,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `divisions_id` PRIMARY KEY(`id`)
);

CREATE TABLE `categories` (
	`id` varchar(32) NOT NULL,
	`name` varchar(80) NOT NULL,
	`description` text NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `categories_id` PRIMARY KEY(`id`)
);

CREATE TABLE `product_specs` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`product_id` varchar(64) NOT NULL,
	`label` varchar(80) NOT NULL,
	`value` varchar(200) NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	CONSTRAINT `product_specs_id` PRIMARY KEY(`id`)
);

CREATE TABLE `products` (
	`id` varchar(64) NOT NULL,
	`slug` varchar(80) NOT NULL,
	`name` varchar(120) NOT NULL,
	`category_id` varchar(32) NOT NULL,
	`price_mmk` bigint NOT NULL,
	`tagline` varchar(200) NOT NULL,
	`description` text NOT NULL,
	`swatch` char(7) NOT NULL,
	`stock_qty` int NOT NULL DEFAULT 0,
	`low_stock_threshold` int NOT NULL DEFAULT 3,
	`has_photos` boolean NOT NULL DEFAULT false,
	`is_active` boolean NOT NULL DEFAULT true,
	`featured` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_slug_unique` UNIQUE(`slug`)
);

CREATE TABLE `payment_methods` (
	`id` varchar(40) NOT NULL,
	`name` varchar(60) NOT NULL,
	`kind` enum('wallet','cod') NOT NULL,
	`account_name` varchar(120),
	`account_phone` varchar(20),
	`qr_image_url` varchar(255),
	`instructions_md` text,
	`sort_order` int NOT NULL DEFAULT 0,
	`is_active` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payment_methods_id` PRIMARY KEY(`id`)
);

CREATE TABLE `order_items` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`order_id` varchar(36) NOT NULL,
	`product_id` varchar(64) NOT NULL,
	`qty` int NOT NULL,
	`unit_price_mmk_snapshot` bigint NOT NULL,
	`name_snapshot` varchar(120) NOT NULL,
	CONSTRAINT `order_items_id` PRIMARY KEY(`id`)
);

CREATE TABLE `orders` (
	`id` varchar(36) NOT NULL,
	`user_id` varchar(36) NOT NULL,
	`status` enum('pending_payment','payment_submitted','confirmed','paid','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending_payment',
	`subtotal_mmk` bigint NOT NULL,
	`delivery_fee_mmk` bigint NOT NULL,
	`total_mmk` bigint NOT NULL,
	`shipping_address_id` varchar(36),
	`payment_method_id` varchar(40) NOT NULL,
	`payment_proof_url` varchar(255),
	`payment_tx_ref` varchar(120),
	`payment_ref` varchar(64),
	`expires_at` timestamp NOT NULL,
	`notes` text,
	`placed_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`)
);

CREATE TABLE `reviews` (
	`id` varchar(36) NOT NULL,
	`product_id` varchar(64) NOT NULL,
	`user_id` varchar(36) NOT NULL,
	`rating` tinyint NOT NULL,
	`title` varchar(120),
	`body` text NOT NULL,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`verified_purchase` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `reviews_id` PRIMARY KEY(`id`),
	CONSTRAINT `uniq_review_user_product` UNIQUE(`user_id`,`product_id`)
);

CREATE TABLE `wishlists` (
	`user_id` varchar(36) NOT NULL,
	`product_id` varchar(64) NOT NULL,
	`added_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `wishlists_user_id_product_id_pk` PRIMARY KEY(`user_id`,`product_id`)
);

CREATE TABLE `newsletter_subscribers` (
	`id` varchar(36) NOT NULL,
	`email` varchar(254) NOT NULL,
	`source` varchar(40) NOT NULL DEFAULT 'homepage',
	`status` enum('active','unsubscribed') NOT NULL DEFAULT 'active',
	`unsubscribe_token` varchar(64) NOT NULL,
	`subscribed_at` timestamp NOT NULL DEFAULT (now()),
	`unsubscribed_at` timestamp,
	CONSTRAINT `newsletter_subscribers_id` PRIMARY KEY(`id`),
	CONSTRAINT `newsletter_subscribers_email_unique` UNIQUE(`email`)
);

ALTER TABLE `addresses` ADD CONSTRAINT `addresses_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `addresses` ADD CONSTRAINT `addresses_division_id_divisions_id_fk` FOREIGN KEY (`division_id`) REFERENCES `divisions`(`id`) ON DELETE restrict ON UPDATE no action;
ALTER TABLE `accounts` ADD CONSTRAINT `accounts_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `sessions` ADD CONSTRAINT `sessions_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `cart_items` ADD CONSTRAINT `cart_items_cart_id_carts_id_fk` FOREIGN KEY (`cart_id`) REFERENCES `carts`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `cart_items` ADD CONSTRAINT `cart_items_product_id_products_id_fk` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `carts` ADD CONSTRAINT `carts_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `product_specs` ADD CONSTRAINT `product_specs_product_id_products_id_fk` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `products` ADD CONSTRAINT `products_category_id_categories_id_fk` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE no action ON UPDATE no action;
ALTER TABLE `order_items` ADD CONSTRAINT `order_items_order_id_orders_id_fk` FOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `order_items` ADD CONSTRAINT `order_items_product_id_products_id_fk` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE no action ON UPDATE no action;
ALTER TABLE `orders` ADD CONSTRAINT `orders_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;
ALTER TABLE `orders` ADD CONSTRAINT `orders_shipping_address_id_addresses_id_fk` FOREIGN KEY (`shipping_address_id`) REFERENCES `addresses`(`id`) ON DELETE set null ON UPDATE no action;
ALTER TABLE `orders` ADD CONSTRAINT `orders_payment_method_id_payment_methods_id_fk` FOREIGN KEY (`payment_method_id`) REFERENCES `payment_methods`(`id`) ON DELETE restrict ON UPDATE no action;
ALTER TABLE `reviews` ADD CONSTRAINT `reviews_product_id_products_id_fk` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `reviews` ADD CONSTRAINT `reviews_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `wishlists` ADD CONSTRAINT `wishlists_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `wishlists` ADD CONSTRAINT `wishlists_product_id_products_id_fk` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE cascade ON UPDATE no action;
CREATE INDEX `idx_addresses_user` ON `addresses` (`user_id`);
CREATE INDEX `idx_accounts_user` ON `accounts` (`userId`);
CREATE INDEX `idx_carts_user` ON `carts` (`user_id`);
CREATE INDEX `idx_carts_session` ON `carts` (`session_id`);
CREATE INDEX `idx_specs_product` ON `product_specs` (`product_id`,`sort_order`);
CREATE INDEX `idx_products_category` ON `products` (`category_id`);
CREATE INDEX `idx_products_featured` ON `products` (`featured`);
CREATE INDEX `idx_products_is_active` ON `products` (`is_active`);
CREATE INDEX `idx_orders_user` ON `orders` (`user_id`);
CREATE INDEX `idx_orders_status` ON `orders` (`status`);
CREATE INDEX `idx_orders_placed` ON `orders` (`placed_at`);
CREATE INDEX `idx_orders_expires` ON `orders` (`status`,`expires_at`);
CREATE INDEX `idx_reviews_product_status` ON `reviews` (`product_id`,`status`);

-- =================================================================
-- 2. Divisions (BeeExpress shipping rates)
-- =================================================================
INSERT INTO `divisions` (`id`, `name`, `delivery_fee_mmk`, `cod_allowed`, `is_blocked`, `sort_order`) VALUES
('mandalay', 'Mandalay Region', 3000, 1, 0, 1),
('yangon', 'Yangon Region', 5000, 1, 0, 2),
('naypyidaw', 'Naypyidaw Union Territory', 5000, 0, 0, 3),
('bago', 'Bago Region', 5750, 0, 0, 4),
('magway', 'Magway Region', 5750, 0, 0, 5),
('ayeyarwady', 'Ayeyarwady Region', 6250, 0, 0, 6),
('chin', 'Chin State', 6250, 0, 0, 7),
('mon', 'Mon State', 6250, 0, 0, 8),
('shan', 'Shan State', 6500, 0, 0, 9),
('rakhine', 'Rakhine State', 7000, 0, 0, 10),
('kachin', 'Kachin State', 8500, 0, 0, 11),
('tanintharyi', 'Tanintharyi Region', 8500, 0, 0, 12),
('kayah', 'Kayah State', 0, 0, 1, 13),
('kayin', 'Kayin State', 0, 0, 1, 14),
('sagaing', 'Sagaing Region', 0, 0, 1, 15);

-- =================================================================
-- 3. Payment methods (all inactive — owner activates via /admin)
-- =================================================================
INSERT INTO `payment_methods` (`id`, `name`, `kind`, `sort_order`, `is_active`) VALUES
('kbz_pay', 'KBZ Pay', 'wallet', 1, 0),
('aya_pay', 'Aya Pay', 'wallet', 2, 0),
('uab_pay', 'UAB Pay', 'wallet', 3, 0),
('kbz_bank', 'KBZ Bank', 'wallet', 4, 0),
('cod', 'Cash on Delivery', 'cod', 5, 0);

-- =================================================================
-- 4. Categories
-- =================================================================
INSERT INTO `categories` (`id`, `name`, `description`, `sort_order`) VALUES
('keyboards', 'Keyboards', 'Mechanical, low-profile, and hot-swap boards built for daily writing — not for tournaments.', 1),
('mice', 'Mice', 'Pointing devices with restraint. Quiet clicks, honest shapes, low-latency wireless.', 2),
('headsets', 'Headsets', 'Over-ear cans tuned for voices and music — wired and wireless.', 3),
('microphones', 'Microphones', 'Desktop USB mics for calls, streams, and clean voice capture.', 4),
('speakers', 'Speakers', 'Compact desk speakers with warmth and presence — no subwoofer required.', 5),
('accessories', 'Accessories', 'Mats, wrist rests, and the small things that finish a desk.', 6);

-- =================================================================
-- 5. Products
-- =================================================================
INSERT INTO `products` (`id`, `slug`, `name`, `category_id`, `price_mmk`, `tagline`, `description`, `swatch`, `stock_qty`, `low_stock_threshold`, `has_photos`, `is_active`, `featured`) VALUES
('hyperx-alloy-origins-core', 'hyperx-alloy-origins-core', 'HyperX Alloy Origins Core', 'keyboards', 361000, 'Tenkeyless wired with tactile aqua switches.', 'A compact aluminium-body TKL with HyperX Aqua tactile switches and per-key RGB. USB-C detachable cable, three adjustable tilt angles.', '#2A2622', 12, 3, 1, 1, 1),
('keychron-k2-pro', 'keychron-k2-pro', 'Keychron K2 Pro', 'keyboards', 545000, '75% hot-swap with tri-mode wireless.', 'Keychron''s flagship 75% in tri-mode. Hot-swap PCB, gasket structure, and QMK/VIA support. Bluetooth, 2.4G, USB-C wired.', '#3D342A', 9, 3, 1, 1, 1),
('nuphy-halo65', 'nuphy-halo65', 'Nuphy Halo65', 'keyboards', 515000, '65% gasket with halo side light.', 'A 65% with a soft gasket structure and a signature halo side light. Tri-mode wireless, hot-swap PCB, Night Breeze or Rose Glacier switches.', '#2C2825', 5, 2, 1, 1, 1),
('vxe-r1se-plus', 'vxe-r1se-plus', 'VXE R1SE+', 'mice', 125000, '55-gram tri-mode at entry-level money.', 'PAW3395SE sensor, 55-gram shell, and tri-mode wireless. The cheapest way into a serious lightweight mouse.', '#E8DCC8', 11, 3, 1, 1, 1),
('logitech-g304', 'logitech-g304', 'Logitech G304', 'mice', 195000, 'LIGHTSPEED wireless, 250-hour battery.', 'The HERO sensor at its most accessible. LIGHTSPEED wireless, AA-powered for 250 hours, six programmable buttons.', '#262320', 13, 3, 1, 1, 1),
('logitech-g-pro-x-superlight-2', 'logitech-g-pro-x-superlight-2', 'Logitech G PRO X Superlight 2', 'mice', 650000, 'Sub-60g flagship. The pro pick.', 'HERO 2 sensor, LIGHTSPEED wireless, and a sub-60-gram shell. The benchmark for high-performance wireless mice.', '#1A1816', 4, 2, 1, 1, 1),
('razer-kraken-x-essential', 'razer-kraken-x-essential', 'Razer Kraken X Essential', 'headsets', 169000, 'Featherweight wired headset. Honest budget pick.', '230 grams on the head, 40 mm drivers, 7.1 surround over USB. A clean entry-level headset that gets out of the way.', '#1A1816', 10, 3, 1, 1, 1),
('hyperx-cloud-iii-wired', 'hyperx-cloud-iii-wired', 'HyperX Cloud III Wired', 'headsets', 459000, '53mm drivers and DTS spatial.', 'The Cloud lineage, refined. 53 mm angled drivers, DTS Headphone:X, detachable mic, USB-C and 3.5 mm out of the box.', '#1F1C1A', 6, 2, 1, 1, 1),
('hyperx-cloud-iii-wireless', 'hyperx-cloud-iii-wireless', 'HyperX Cloud III Wireless', 'headsets', 690000, '120-hour battery. DTS spatial.', 'Cloud III over 2.4 GHz with 120-hour battery, DTS spatial audio, 53 mm angled drivers, detachable mic.', '#2A2622', 4, 2, 1, 1, 1),
('hyperx-solocast', 'hyperx-solocast', 'HyperX SoloCast', 'microphones', 289000, 'Cardioid USB mic with tap-mute.', 'A plug-and-play USB condenser. Cardioid pickup, tap-to-mute on top, 24-bit/96 kHz capture, adjustable stand.', '#1C1A18', 9, 2, 1, 1, 1),
('hyperx-quadcast-s', 'hyperx-quadcast-s', 'HyperX QuadCast S', 'microphones', 750000, 'Four polar patterns. RGB shock-mount.', 'The full-featured streamer mic. Four polar patterns, anti-vibration mount, headphone monitoring jack, 24-bit/96 kHz capture.', '#28231F', 3, 1, 1, 1, 0),
('edifier-m230-retro-brown', 'edifier-m230-retro-brown', 'Edifier M230 Retro Brown', 'speakers', 320000, '20W desk speaker with BT 5.0.', 'A retro-styled desk speaker with 20 watts, BT 5.0, AUX, USB-C, and TF input. Ten-hour battery for desk-to-shelf moves.', '#7A4F36', 6, 2, 1, 1, 1),
('premium-deskmat', 'premium-deskmat', 'Premium DeskMat', 'accessories', 60600, '900x400, 4mm cloth, washable.', 'A 900x400 mm cloth deskmat with non-slip backing and stitched edges. Washable, four millimetres thick.', '#4A3E33', 16, 4, 1, 1, 1),
('mouse-wrist-rest', 'mouse-wrist-rest', 'Mouse Wrist Rest', 'accessories', 25000, 'Ergonomic support for long days.', 'A contoured wrist rest sized for mouse pads. Memory foam core, fabric top, anti-slip base.', '#3D342A', 20, 5, 1, 1, 1),
('8in1-cleaning-kit', '8in1-cleaning-kit', '8-in-1 Cleaning Kit', 'accessories', 19500, 'For keyboards, earbuds, phones, tablets.', 'Eight tools in one kit: brush, swab, putty, microfiber, spray bottle, and key-pullers. Covers the full desk surface.', '#5A4A3E', 18, 4, 1, 1, 1);

-- =================================================================
-- 6. Product specs
-- =================================================================
INSERT INTO `product_specs` (`product_id`, `label`, `value`, `sort_order`) VALUES
('hyperx-alloy-origins-core', 'Layout', 'TKL (87 keys)', 0),
('hyperx-alloy-origins-core', 'Switches', 'HyperX Aqua Tactile', 1),
('hyperx-alloy-origins-core', 'Lighting', 'Per-key RGB', 2),
('hyperx-alloy-origins-core', 'Connection', 'USB-C, detachable', 3),
('keychron-k2-pro', 'Layout', '75% (84 keys)', 0),
('keychron-k2-pro', 'Switches', 'Hot-swap, Brown or Red', 1),
('keychron-k2-pro', 'Connection', 'BT 5.1 + 2.4G + USB-C', 2),
('keychron-k2-pro', 'Firmware', 'QMK / VIA', 3),
('nuphy-halo65', 'Layout', '65% (68 keys)', 0),
('nuphy-halo65', 'Mount', 'Gasket', 1),
('nuphy-halo65', 'Switches', 'Hot-swap, Night Breeze / Rose Glacier', 2),
('nuphy-halo65', 'Connection', 'BT + 2.4G + USB-C', 3),
('vxe-r1se-plus', 'Sensor', 'PixArt PAW3395SE', 0),
('vxe-r1se-plus', 'Weight', '55 g', 1),
('vxe-r1se-plus', 'Connection', 'BT + 2.4G + USB-C', 2),
('vxe-r1se-plus', 'Battery', '70 hours', 3),
('logitech-g304', 'Sensor', 'HERO 12K', 0),
('logitech-g304', 'Connection', 'LIGHTSPEED 2.4G', 1),
('logitech-g304', 'Battery', '250 hours (AA)', 2),
('logitech-g304', 'Buttons', '6 programmable', 3),
('logitech-g-pro-x-superlight-2', 'Sensor', 'HERO 2, 32000 DPI', 0),
('logitech-g-pro-x-superlight-2', 'Weight', '< 60 g', 1),
('logitech-g-pro-x-superlight-2', 'Connection', 'LIGHTSPEED 2.4G + USB-C', 2),
('logitech-g-pro-x-superlight-2', 'Battery', '95 hours', 3),
('razer-kraken-x-essential', 'Drivers', '40 mm', 0),
('razer-kraken-x-essential', 'Surround', '7.1 (software)', 1),
('razer-kraken-x-essential', 'Weight', '230 g', 2),
('razer-kraken-x-essential', 'Connection', '3.5 mm', 3),
('hyperx-cloud-iii-wired', 'Drivers', '53 mm angled', 0),
('hyperx-cloud-iii-wired', 'Audio', 'DTS Headphone:X spatial', 1),
('hyperx-cloud-iii-wired', 'Mic', 'Detachable', 2),
('hyperx-cloud-iii-wired', 'Connection', 'USB-C / USB-A / 3.5 mm', 3),
('hyperx-cloud-iii-wireless', 'Drivers', '53 mm angled', 0),
('hyperx-cloud-iii-wireless', 'Audio', 'DTS Headphone:X spatial', 1),
('hyperx-cloud-iii-wireless', 'Battery', '120 hours', 2),
('hyperx-cloud-iii-wireless', 'Connection', '2.4G + USB-C', 3),
('hyperx-solocast', 'Pattern', 'Cardioid', 0),
('hyperx-solocast', 'Sample', '24-bit / 96 kHz', 1),
('hyperx-solocast', 'Control', 'Tap-to-mute, LED indicator', 2),
('hyperx-solocast', 'Connection', 'USB-C', 3),
('hyperx-quadcast-s', 'Patterns', 'Cardioid / Stereo / Omni / Bidirectional', 0),
('hyperx-quadcast-s', 'Sample', '24-bit / 96 kHz', 1),
('hyperx-quadcast-s', 'Features', 'Tap-mute, headphone monitor, RGB', 2),
('hyperx-quadcast-s', 'Connection', 'USB-C', 3),
('edifier-m230-retro-brown', 'Output', '20 W', 0),
('edifier-m230-retro-brown', 'Connectivity', 'BT 5.0 / AUX / USB-C / TF', 1),
('edifier-m230-retro-brown', 'Battery', '10 hours', 2),
('edifier-m230-retro-brown', 'Finish', 'Retro Brown', 3),
('premium-deskmat', 'Size', '900 × 400 mm', 0),
('premium-deskmat', 'Thickness', '4 mm', 1),
('premium-deskmat', 'Surface', 'Cloth, non-slip rubber base', 2),
('premium-deskmat', 'Care', 'Machine washable', 3),
('mouse-wrist-rest', 'Core', 'Memory foam', 0),
('mouse-wrist-rest', 'Top', 'Fabric', 1),
('mouse-wrist-rest', 'Base', 'Anti-slip', 2),
('8in1-cleaning-kit', 'Tools', '8 pieces', 0),
('8in1-cleaning-kit', 'Targets', 'Keyboard / earbuds / phone / tablet', 1),
('8in1-cleaning-kit', 'Form', 'Compact case', 2);

-- =================================================================
-- Bootstrap complete.
-- Next steps (manual, via SSH or phpMyAdmin):
--   UPDATE users SET role='admin' WHERE email='you@example.com';
-- =================================================================
